import type { Metadata } from "next";
import { NewsletterForm } from "../components/NewsletterForm";
import { PageHero } from "../components/PageHero";

export const metadata: Metadata = { title: "Insights", description: "Perspectives from BioPancrea on pancreatic biology, company thinking, and responsible innovation." };
const categories = ["Perspectives", "Company updates", "Pancreatic biology", "Responsible innovation"];

export default function InsightsPage() {
  return <main>
    <PageHero index="04" label="Insights" title="Ideas worth looking at closely." copy="A growing editorial space for perspectives on pancreatic health, scientific attention, and responsible progress." />
    <section className="insight-index container"><div className="category-row" aria-label="Insight categories">{categories.map((category,index) => <span key={category}><i>0{index + 1}</i>{category}</span>)}</div><article className="featured-insight"><div className="article-art" aria-hidden="true"><i /><i /><i /><span /></div><div><p className="article-meta">Perspectives · 6 minute read</p><h2>Why pancreatic health deserves greater attention</h2><p>The pancreas sits at the intersection of several systems that sustain everyday human health. That connected role makes it both important and complex—and makes focused scientific attention especially valuable.</p><a className="inline-link" href="#article">Read perspective <span aria-hidden="true">↓</span></a></div></article></section>
    <article className="editorial-article container" id="article"><header><p className="section-label"><span>Perspective 001</span>Pancreatic health</p><h2>Why pancreatic health deserves greater attention</h2><p className="standfirst">Sometimes meaningful progress begins not with a new answer, but with renewed attention to an important question.</p></header><div className="article-body"><p className="drop-cap">The pancreas participates in a remarkable range of biological activity. It contributes to processes involved in digestion, endocrine signalling, and metabolic balance—roles that are closely connected to wider human health.</p><p>That interconnectedness also brings complexity. Looking at pancreatic health in isolation can miss the wider systems in which it participates. A deeper view invites perspectives from biology, medicine, technology, and the lived human context.</p><h3>Attention is a starting point</h3><p>Scientific progress depends on asking clear questions, examining assumptions, and creating the conditions for careful exploration. Greater attention does not guarantee simple answers, but it can expand what becomes possible to understand.</p><p>For BioPancrea, that means approaching the field with curiosity and discipline: remaining open to new connections while staying grounded in evidence and responsibility.</p><aside>This article provides general educational information only and does not provide medical advice.</aside></div></article>
    <section className="newsletter-section container"><div><p className="section-label light"><span>Updates</span>Stay in touch</p><h2>Quiet progress.<br />Shared thoughtfully.</h2></div><NewsletterForm /></section>
  </main>;
}
